language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: heroku
  api_key:
    secure: mBI/Hpy1KkPOU7t7hDBEN13bBmpnQxx5ZRvCDkPlu3htUDu9uQTbQ6FP1E9RxIP7Y4NdH0GsNy3LE3wywym839Vd+66nh2Y4i8gmhAn57KPy+wwjA45Hve9zjZlsFrgB8Vdd+vSeW5TJfBf2+bvoJ4LX0kTzn2cTOQRoE+0ytAk6zHCFV2xtK4ywaTG2YpYoYhv+33cYOJ9PltAORpWWM8bB5MGVqR7tS5DrNkLxmdqq/HJYuCiLfGvrQZBVzzEcdyFnZ/6ixqQcz2tuc0ukjShqaMJqtH+LfWf1tc93nljko09czv2rkRRnIwPSEsIE9RM304FgwelEW1JfmPa4whYNjtWgK97Ie+8z+d3ruKst2NLj7Bod00eLnOl09G2EsPfknuOJ2MDUZv65sb9JvbwFbyiI0m7LpKlsMhgmBolfmGpDuX/5fWdaA2aaOYuIfrvtBC3EUGq/DEO861jvIoBLKFMI3UhseUZfUfnvYu0x87n9Ht3/2ZNFGDm0slokvNvKusQTQgqN9WU+7v34aNuTVsuvuFF1L4PJPYMNie1Plw6N5Ge1h4YmbCMk8nAAioEs8oup1gWpwk5AvD/gJINyH6PS4w/sVtJNjhQYF8cfid8T2V3CGAC6cybcIjSsYL8NDAfHYpMSv+cmO/nTVH6preLvw0yW/8mOuJTdZw0=
  app: spring-bookstore
  on:
    repo: nadeva/spring-bookstore